title: Building a Computer Vision Application Leveraging the Custom Vision Service
description: Microsoft labs for learning to develop with the Custom Vision Service
show_downloads: true
theme: jekyll-theme-cayman
repository: Azure/learnAnalytics-Buildingacomputervisionapplicationleveragingthecustomvisionservice